name: Deploy Spring Boot App with Docker Compose

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      REDIS_PASSWORD:
      ELASTIC_PASSWORD: ${{ secrets.ELASTIC_SEARCH_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 기존 Build Docker image 대신 사용(AMD64와 ARM64 이미지를 모두 생성)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image (Multi-arch)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8 # 빌드할 아키텍처 명시
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/group_platform:latest

        #이렇게 되면 AMD64경고가 뜸. 현재 맥 환경과 안맞음
#      - name: Build Docker image
#        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/group_platform:latest .
#
#      - name: Push Docker image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/group_platform:latest




#      - name: Deploy with docker-compose
#        run: |
#          docker compose pull
#          docker compose up -d